title: אוצר תורה - וילנסקי
description: חידושי תורה, פנינים וורטים - מורשת משפחת וילנסקי לדורות
baseurl: "" 
url: "https://vilenskytorah.github.io"
lang: he
rtl: true

# GitHub
repository: vilenskytorah/torah-archive

# Collections
collections:
  chidushim:
    output: true
    permalink: /chidush/:title/
  pninim:
    output: true
    permalink: /pnina/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "chidushim"
    values:
      layout: chidush
  - scope:
      path: ""
      type: "pninim"
    values:
      layout: pnina

# Sass
sass:
  sass_dir: _sass
  style: compressed
