title: אוצר תורה
description: חידושי תורה, פנינים וורטים - מורשת משפחת וילנסקי
baseurl: "/torah-archive"   # חשוב מאוד!
url: "https://vilenskytorah.github.io"

lang: he
rtl: true

collections:
  chidushim:
    output: true
  pninim:
    output: true
