title: אוצר החידושים
description: חידושי תורה של משפחת דוד וילנסקי - מורשת לדורות
baseurl: ""  # אם הריפו הוא vilenskytorah.github.io אז השאר ריק
url: "https://vilenskytorah.github.io"
lang: he
rtl: true

github_username: vilenskytorah
repository: torah-archive

# Collections
collections:
  chidushim:
    output: true
    permalink: /chidush/:title/
  pninim:
    output: true
    permalink: /pnina/:title/

defaults:
  - scope:
      path: ""
      type: "chidushim"
    values:
      layout: chidush
      author: "דוד וילנסקי"
